Bump devise to 4.8.0
Old version was causing syntax errors when unicorn was coming up:

```
SyntaxError: /app/vendor/bundle/ruby/2.5.0/gems/devise-3.4.1/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '{', expecting keyword_end
...r only: [ :create, :destroy ] { request.env["devise.skip_tim...
...                              ^
/app/vendor/bundle/ruby/2.5.0/gems/devise-3.4.1/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '}', expecting keyword_end
..."devise.skip_timeout"] = true }
```